name: github-pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /Conholdate.Total/
          dst_path: /content/Conholdate.Total/
          dst_owner: conholdate
          dst_repo_name: conholdate-blog
